name: need_in_choice
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  smooth_page_indicator: ^1.1.0
  dotted_border: ^2.0.0+3
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.3
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tools/
    - assets/images/profile/
    - assets/images/category/level1-main-category/
    - assets/images/category/level3-sub-cat/
    - assets/images/category/level4-sub-cat/
    - assets/images/category/vehicles-rent/
    - assets/images/dummy/
    - assets/images/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
